### ISSUE TITLE
"Start player" feature not load player on button click

### ISSUE THREAD

**Issue by MurzNN** [bkueng/mediacontrollercompact#1]
In "Start player" field of plasmoid settings I put full path to my favorite media player (`/usr/bin/MellowPlayer`). 

When MellowPlayer is unloaded - widget shows only one "play" button with "No media playing" popup. But when I click on that button or on any other place in plasmoid - it don't load my player, and don't do anything else.

Does this feature must work like described? If yes, how can I debug where can be the problem?

**Comment by bkueng** [comment]
Yes this works for me. A few things you can try:
- Make sure you have the path correct by executing `/usr/bin/MellowPlayer` on the shell
- Change the entry to `echo test > /tmp/file` and check if that file gets created.

For referece, it's executed here: https://github.com/bkueng/mediacontrollercompact/blob/master/package/contents/ui/ExpandedRepresentation.qml#L156.

**Comment by MurzNN** [comment]
Command `echo test > /tmp/file` works well, seems some problem with `MellowPlayer` startup.

**Comment by MurzNN** [comment]
Solved via redirecting output to file using `/usr/bin/MellowPlayer > /tmp/mp-output.txt`
